volumes:
  OsawaKousei.github.io-node-modules:

services:
  OsawaKousei.github.io-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/app:/app
      - OsawaKousei.github.io-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - OsawaKousei.github.io-app-network

networks:
  OsawaKousei.github.io-app-network:
    driver: bridge